# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/janus.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'v1/janus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ev1/janus.proto\x12\x08janus.v1\";\n\x11InspectionRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nraw_prompt\x18\x02 \x01(\t\"^\n\x12InspectionResponse\x12 \n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x10.janus.v1.Action\x12\x16\n\x0emutated_prompt\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t*V\n\x06\x41\x63tion\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x41\x43TION_ALLOW\x10\x01\x12\x0f\n\x0b\x41\x43TION_DENY\x10\x02\x12\x11\n\rACTION_MUTATE\x10\x03\x32\\\n\x0eSecurityEngine\x12J\n\rInspectPrompt\x12\x1b.janus.v1.InspectionRequest\x1a\x1c.janus.v1.InspectionResponseB\x1bZ\x19janus/internal/pb/v1;pbv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.janus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031janus/internal/pb/v1;pbv1'
  _globals['_ACTION']._serialized_start=185
  _globals['_ACTION']._serialized_end=271
  _globals['_INSPECTIONREQUEST']._serialized_start=28
  _globals['_INSPECTIONREQUEST']._serialized_end=87
  _globals['_INSPECTIONRESPONSE']._serialized_start=89
  _globals['_INSPECTIONRESPONSE']._serialized_end=183
  _globals['_SECURITYENGINE']._serialized_start=273
  _globals['_SECURITYENGINE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
