// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: v1/janus.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_ALLOW       Action = 1
	Action_ACTION_DENY        Action = 2
	Action_ACTION_MUTATE      Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ALLOW",
		2: "ACTION_DENY",
		3: "ACTION_MUTATE",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_ALLOW":       1,
		"ACTION_DENY":        2,
		"ACTION_MUTATE":      3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_janus_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_v1_janus_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_v1_janus_proto_rawDescGZIP(), []int{0}
}

// Sent from Go proxy --> Python Service
type InspectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RawPrompt     string                 `protobuf:"bytes,2,opt,name=raw_prompt,json=rawPrompt,proto3" json:"raw_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectionRequest) Reset() {
	*x = InspectionRequest{}
	mi := &file_v1_janus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectionRequest) ProtoMessage() {}

func (x *InspectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_janus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectionRequest.ProtoReflect.Descriptor instead.
func (*InspectionRequest) Descriptor() ([]byte, []int) {
	return file_v1_janus_proto_rawDescGZIP(), []int{0}
}

func (x *InspectionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InspectionRequest) GetRawPrompt() string {
	if x != nil {
		return x.RawPrompt
	}
	return ""
}

// Sent from Python Service --> to Go Proxy
type InspectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        Action                 `protobuf:"varint,1,opt,name=action,proto3,enum=janus.v1.Action" json:"action,omitempty"`
	MutatedPrompt string                 `protobuf:"bytes,2,opt,name=mutated_prompt,json=mutatedPrompt,proto3" json:"mutated_prompt,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectionResponse) Reset() {
	*x = InspectionResponse{}
	mi := &file_v1_janus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectionResponse) ProtoMessage() {}

func (x *InspectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_janus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectionResponse.ProtoReflect.Descriptor instead.
func (*InspectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_janus_proto_rawDescGZIP(), []int{1}
}

func (x *InspectionResponse) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *InspectionResponse) GetMutatedPrompt() string {
	if x != nil {
		return x.MutatedPrompt
	}
	return ""
}

func (x *InspectionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_v1_janus_proto protoreflect.FileDescriptor

const file_v1_janus_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/janus.proto\x12\bjanus.v1\"Q\n" +
	"\x11InspectionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"raw_prompt\x18\x02 \x01(\tR\trawPrompt\"}\n" +
	"\x12InspectionResponse\x12(\n" +
	"\x06action\x18\x01 \x01(\x0e2\x10.janus.v1.ActionR\x06action\x12%\n" +
	"\x0emutated_prompt\x18\x02 \x01(\tR\rmutatedPrompt\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*V\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fACTION_ALLOW\x10\x01\x12\x0f\n" +
	"\vACTION_DENY\x10\x02\x12\x11\n" +
	"\rACTION_MUTATE\x10\x032\\\n" +
	"\x0eSecurityEngine\x12J\n" +
	"\rInspectPrompt\x12\x1b.janus.v1.InspectionRequest\x1a\x1c.janus.v1.InspectionResponseB\x1bZ\x19janus/internal/pb/v1;pbv1b\x06proto3"

var (
	file_v1_janus_proto_rawDescOnce sync.Once
	file_v1_janus_proto_rawDescData []byte
)

func file_v1_janus_proto_rawDescGZIP() []byte {
	file_v1_janus_proto_rawDescOnce.Do(func() {
		file_v1_janus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_janus_proto_rawDesc), len(file_v1_janus_proto_rawDesc)))
	})
	return file_v1_janus_proto_rawDescData
}

var file_v1_janus_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_janus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_janus_proto_goTypes = []any{
	(Action)(0),                // 0: janus.v1.Action
	(*InspectionRequest)(nil),  // 1: janus.v1.InspectionRequest
	(*InspectionResponse)(nil), // 2: janus.v1.InspectionResponse
}
var file_v1_janus_proto_depIdxs = []int32{
	0, // 0: janus.v1.InspectionResponse.action:type_name -> janus.v1.Action
	1, // 1: janus.v1.SecurityEngine.InspectPrompt:input_type -> janus.v1.InspectionRequest
	2, // 2: janus.v1.SecurityEngine.InspectPrompt:output_type -> janus.v1.InspectionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_janus_proto_init() }
func file_v1_janus_proto_init() {
	if File_v1_janus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_janus_proto_rawDesc), len(file_v1_janus_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_janus_proto_goTypes,
		DependencyIndexes: file_v1_janus_proto_depIdxs,
		EnumInfos:         file_v1_janus_proto_enumTypes,
		MessageInfos:      file_v1_janus_proto_msgTypes,
	}.Build()
	File_v1_janus_proto = out.File
	file_v1_janus_proto_goTypes = nil
	file_v1_janus_proto_depIdxs = nil
}
