// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: v1/janus.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecurityEngine_InspectPrompt_FullMethodName = "/janus.v1.SecurityEngine/InspectPrompt"
)

// SecurityEngineClient is the client API for SecurityEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Security Engine service running in Python
type SecurityEngineClient interface {
	InspectPrompt(ctx context.Context, in *InspectionRequest, opts ...grpc.CallOption) (*InspectionResponse, error)
}

type securityEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityEngineClient(cc grpc.ClientConnInterface) SecurityEngineClient {
	return &securityEngineClient{cc}
}

func (c *securityEngineClient) InspectPrompt(ctx context.Context, in *InspectionRequest, opts ...grpc.CallOption) (*InspectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectionResponse)
	err := c.cc.Invoke(ctx, SecurityEngine_InspectPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityEngineServer is the server API for SecurityEngine service.
// All implementations must embed UnimplementedSecurityEngineServer
// for forward compatibility.
//
// The Security Engine service running in Python
type SecurityEngineServer interface {
	InspectPrompt(context.Context, *InspectionRequest) (*InspectionResponse, error)
	mustEmbedUnimplementedSecurityEngineServer()
}

// UnimplementedSecurityEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecurityEngineServer struct{}

func (UnimplementedSecurityEngineServer) InspectPrompt(context.Context, *InspectionRequest) (*InspectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectPrompt not implemented")
}
func (UnimplementedSecurityEngineServer) mustEmbedUnimplementedSecurityEngineServer() {}
func (UnimplementedSecurityEngineServer) testEmbeddedByValue()                        {}

// UnsafeSecurityEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityEngineServer will
// result in compilation errors.
type UnsafeSecurityEngineServer interface {
	mustEmbedUnimplementedSecurityEngineServer()
}

func RegisterSecurityEngineServer(s grpc.ServiceRegistrar, srv SecurityEngineServer) {
	// If the following call panics, it indicates UnimplementedSecurityEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecurityEngine_ServiceDesc, srv)
}

func _SecurityEngine_InspectPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityEngineServer).InspectPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityEngine_InspectPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityEngineServer).InspectPrompt(ctx, req.(*InspectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityEngine_ServiceDesc is the grpc.ServiceDesc for SecurityEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "janus.v1.SecurityEngine",
	HandlerType: (*SecurityEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InspectPrompt",
			Handler:    _SecurityEngine_InspectPrompt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/janus.proto",
}
